package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 23 04:04:39 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhrHmoTrxHdr_EOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxhrHmoTrxHdr_EOViewImpl() {
    }

    /**
     * Returns the variable value for BV_TRX_HDR_ID.
     * @return variable value for BV_TRX_HDR_ID
     */
    public String getBV_TRX_HDR_ID() {
        return (String) ensureVariableManager().getVariableValue("BV_TRX_HDR_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_TRX_HDR_ID.
     * @param value value to bind as BV_TRX_HDR_ID
     */
    public void setBV_TRX_HDR_ID(String value) {
        ensureVariableManager().setVariableValue("BV_TRX_HDR_ID", value);
    }
}

