package model.am;

import java.sql.CallableStatement;

import model.am.common.Oando_AM;

import model.ro.XxhrHmoMasterHdr_ROVOImpl;

import model.ro.XxhrHmoTrxHdr_Ex_Emp_ROVOImpl;

import model.svo.LookupType_SVOImpl;

import model.vo.XxExEmpAttachment_EOViewImpl;
import model.vo.XxfndAttachment_EOViewImpl;
import model.vo.XxhrHmoTrxDtl_EOViewImpl;
import model.vo.XxhrHmoTrxHdr_EOViewImpl;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import java.sql.Types;

import java.util.ArrayList;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 09 11:33:37 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Oando_AMImpl extends ApplicationModuleImpl implements Oando_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Oando_AMImpl() {
    }

    /**
     * Container's getter for BUPA_Option_LOV.
     * @return BUPA_Option_LOV
     */
    public ViewObjectImpl getBUPA_Option_LOV() {
        return (ViewObjectImpl) findViewObject("BUPA_Option_LOV");
    }

    /**
     * Container's getter for XxperEmployee_V_ROVO1.
     * @return XxperEmployee_V_ROVO1
     */
    public ViewObjectImpl getXxperEmployee_V_ROVO1() {
        return (ViewObjectImpl) findViewObject("XxperEmployee_V_ROVO1");
    }

    /**
     * Container's getter for SelfDependent_ROVO.
     * @return SelfDependent_ROVO
     */
    public ViewObjectImpl getSelfDependent_ROVO() {
        return (ViewObjectImpl) findViewObject("SelfDependent_ROVO");
    }

    /**
     * Container's getter for XxhrHmoTrxHdr_EOView.
     * @return XxhrHmoTrxHdr_EOView
     */
    public XxhrHmoTrxHdr_EOViewImpl getXxhrHmoTrxHdr_EOView() {
        return (XxhrHmoTrxHdr_EOViewImpl) findViewObject("XxhrHmoTrxHdr_EOView");
    }

    /**
     * Container's getter for XxhrHmoTrxDtl_EOView.
     * @return XxhrHmoTrxDtl_EOView
     */
    public XxhrHmoTrxDtl_EOViewImpl getXxhrHmoTrxDtl_EOView() {
        return (XxhrHmoTrxDtl_EOViewImpl) findViewObject("XxhrHmoTrxDtl_EOView");
    }

    /**
     * Container's getter for LookupType_SVO1.
     * @return LookupType_SVO1
     */
    public LookupType_SVOImpl getLookupType_SVO1() {
        return (LookupType_SVOImpl) findViewObject("LookupType_SVO1");
    }

    /**
     * Container's getter for BUPA_Cat_LOV.
     * @return BUPA_Cat_LOV
     */
    public ViewObjectImpl getBUPA_Cat_LOV() {
        return (ViewObjectImpl) findViewObject("BUPA_Cat_LOV");
    }

    /**
     * Container's getter for TRA_Option_LOV.
     * @return TRA_Option_LOV
     */
    public ViewObjectImpl getTRA_Option_LOV() {
        return (ViewObjectImpl) findViewObject("TRA_Option_LOV");
    }

    /**
     * Container's getter for TRA_Cat_LOV.
     * @return TRA_Cat_LOV
     */
    public ViewObjectImpl getTRA_Cat_LOV() {
        return (ViewObjectImpl) findViewObject("TRA_Cat_LOV");
    }

    /**
     * Container's getter for XxhrHmoMasterHdr_ROVO.
     * @return XxhrHmoMasterHdr_ROVO
     */
    public XxhrHmoMasterHdr_ROVOImpl getXxhrHmoMasterHdr_ROVO() {
        return (XxhrHmoMasterHdr_ROVOImpl) findViewObject("XxhrHmoMasterHdr_ROVO");
    }

    /**
     * Container's getter for Title_LOV.
     * @return Title_LOV
     */
    public ViewObjectImpl getTitle_LOV() {
        return (ViewObjectImpl) findViewObject("Title_LOV");
    }

    /**
     * Container's getter for Gender_LOV.
     * @return Gender_LOV
     */
    public ViewObjectImpl getGender_LOV() {
        return (ViewObjectImpl) findViewObject("Gender_LOV");
    }

    /**
     * Container's getter for OtherDependents_LOV.
     * @return OtherDependents_LOV
     */
    public ViewObjectImpl getOtherDependents_LOV() {
        return (ViewObjectImpl) findViewObject("OtherDependents_LOV");
    }

    /**
     * Container's getter for MaritalStatus_LOV.
     * @return MaritalStatus_LOV
     */
    public ViewObjectImpl getMaritalStatus_LOV() {
        return (ViewObjectImpl) findViewObject("MaritalStatus_LOV");
    }

    /**
     * Container's getter for SearchHMOTrxHdr_ROVO.
     * @return SearchHMOTrxHdr_ROVO
     */
    public ViewObjectImpl getSearchHMOTrxHdr_ROVO() {
        return (ViewObjectImpl) findViewObject("SearchHMOTrxHdr_ROVO");
    }

    /**
     * Container's getter for XxhrHmoHdr_Dtl_VL.
     * @return XxhrHmoHdr_Dtl_VL
     */
    public ViewLinkImpl getXxhrHmoHdr_Dtl_VL() {
        return (ViewLinkImpl) findViewLink("XxhrHmoHdr_Dtl_VL");
    }

    /**
     * gets the current existing database connection
     * @return Connection-Object
     */
    public Connection getCurrentConnection() {
        Statement st = null;
        try {
            st = getDBTransaction().createStatement(0);
            return st.getConnection();
        } catch (Exception s) {
            s.printStackTrace();
            return null;
        } finally {
            if (st != null)
                try {
                    st.close();
                } catch (Exception s2) {
                }
        }
    }


    /**
     * Container's getter for HMOApprovalCount_ROVO1.
     * @return HMOApprovalCount_ROVO1
     */
    public ViewObjectImpl getHMOApprovalCount_ROVO() {
        return (ViewObjectImpl) findViewObject("HMOApprovalCount_ROVO");
    }

    /**
     * Container's getter for XxfndAttachment_EOView1.
     * @return XxfndAttachment_EOView1
     */
    public XxfndAttachment_EOViewImpl getXxfndAttachment_EOView() {
        return (XxfndAttachment_EOViewImpl) findViewObject("XxfndAttachment_EOView");
    }

    /**
     * Container's getter for HMOOtherRequestCount_ROVO1.
     * @return HMOOtherRequestCount_ROVO1
     */
    public ViewObjectImpl getHMOOtherRequestCount_ROVO() {
        return (ViewObjectImpl) findViewObject("HMOOtherRequestCount_ROVO");
    }

    /**
     * Container's getter for SearchHMOOtherRequests_ROVO1.
     * @return SearchHMOOtherRequests_ROVO1
     */
    public ViewObjectImpl getSearchHMOOtherRequests_ROVO() {
        return (ViewObjectImpl) findViewObject("SearchHMOOtherRequests_ROVO");
    }

    /**
     * Container's getter for XxhrHmoCard_VO1.
     * @return XxhrHmoCard_VO1
     */
    public ViewObjectImpl getHMOCard_VO() {
        return (ViewObjectImpl) findViewObject("HMOCard_VO");
    }

    /**
     * Container's getter for XxhrHmoComplaint_VO1.
     * @return XxhrHmoComplaint_VO1
     */
    public ViewObjectImpl getHMOComplaint_VO() {
        return (ViewObjectImpl) findViewObject("HMOComplaint_VO");
    }

    /**
     * Container's getter for XxhrHmoMaintance_VO1.
     * @return XxhrHmoMaintance_VO1
     */
    public ViewObjectImpl getHMOMaintance_VO() {
        return (ViewObjectImpl) findViewObject("HMOMaintance_VO");
    }

    /**
     * Container's getter for XxhrHmoReimbursement_VO1.
     * @return XxhrHmoReimbursement_VO1
     */
    public ViewObjectImpl getHMOReimbursement_VO() {
        return (ViewObjectImpl) findViewObject("HMOReimbursement_VO");
    }

    /**
     * Container's getter for XxhrHmoHdr_VO1.
     * @return XxhrHmoHdr_VO1
     */
    public ViewObjectImpl getNewDepHmoHdr_VO() {
        return (ViewObjectImpl) findViewObject("NewDepHmoHdr_VO");
    }

    /**
     * Container's getter for XxhrHmoDtl_VO1.
     * @return XxhrHmoDtl_VO1
     */
    public ViewObjectImpl getNewDepHmoDtl_VO() {
        return (ViewObjectImpl) findViewObject("NewDepHmoDtl_VO");
    }

    /**
     * Container's getter for NewDep_HdrDtl_VL1.
     * @return NewDep_HdrDtl_VL1
     */
    public ViewLinkImpl getNewDep_HdrDtl_VL1() {
        return (ViewLinkImpl) findViewLink("NewDep_HdrDtl_VL1");
    }
    
    public String updateNewApprovedDependent(String hmo_ref_no) {
        String msg = "";
        try {
            Number hmo_ref = new Number(hmo_ref_no);
            String stmt1 = "BEGIN XXHR_HMO_PKG.UPDATE_APPROVED_NEW_DEPENDENTS(:I_HMO_NEW_ID,:O_ERROR_MSG); END;";
            CallableStatement st = null;
            st = this.getDBTransaction().createCallableStatement(stmt1, 0);
            st.setObject("I_HMO_NEW_ID", hmo_ref);
            st.registerOutParameter("O_ERROR_MSG", Types.VARCHAR);
            st.executeUpdate();
            
            if (st.getObject("O_ERROR_MSG") != null) {
                 msg = st.getObject("O_ERROR_MSG").toString();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return msg;
    }

    /**
     * Container's getter for XxExEmpAttachment_EOView1.
     * @return XxExEmpAttachment_EOView1
     */
    public XxExEmpAttachment_EOViewImpl getXxExEmpAttachment_EOView1() {
        return (XxExEmpAttachment_EOViewImpl) findViewObject("XxExEmpAttachment_EOView1");
    }

    /**
     * Container's getter for XxhrHmoHdr_XxExEmpAttach_VL1.
     * @return XxhrHmoHdr_XxExEmpAttach_VL1
     */
    public ViewLinkImpl getXxhrHmoHdr_XxExEmpAttach_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrHmoHdr_XxExEmpAttach_VL1");
    }

    /**
     * Container's getter for XxhrHmoTrxHdr_Ex_Emp_ROVO1.
     * @return XxhrHmoTrxHdr_Ex_Emp_ROVO1
     */
    public XxhrHmoTrxHdr_Ex_Emp_ROVOImpl getXxhrHmoTrxHdr_Ex_Emp_ROVO1() {
        return (XxhrHmoTrxHdr_Ex_Emp_ROVOImpl) findViewObject("XxhrHmoTrxHdr_Ex_Emp_ROVO1");
    }

    /**
     * Container's getter for XxperExEmployee_V_ROVO1.
     * @return XxperExEmployee_V_ROVO1
     */
    public ViewObjectImpl getXxperExEmployee_V_ROVO() {
        return (ViewObjectImpl) findViewObject("XxperExEmployee_V_ROVO");
    }

    /**
     * Container's getter for HMOExEmpApprovalCount_ROVO1.
     * @return HMOExEmpApprovalCount_ROVO1
     */
    public ViewObjectImpl getHMOExEmpApprovalCount_ROVO() {
        return (ViewObjectImpl) findViewObject("HMOExEmpApprovalCount_ROVO");
    }

    /**
     * Container's getter for SearchExEmpHMOOtherReq_ROVO1.
     * @return SearchExEmpHMOOtherReq_ROVO1
     */
    public ViewObjectImpl getSearchExEmpHMOOtherReq_ROVO() {
        return (ViewObjectImpl) findViewObject("SearchExEmpHMOOtherReq_ROVO");
    }

    /**
     * Container's getter for ExEmpHMOOtherReqCount_ROVO1.
     * @return ExEmpHMOOtherReqCount_ROVO1
     */
    public ViewObjectImpl getExEmpHMOOtherReqCount_ROVO() {
        return (ViewObjectImpl) findViewObject("ExEmpHMOOtherReqCount_ROVO");
    }
}

